#context:
#  initializer:
#    classes: com.example.bootstarp.SpringNettyBootstarp
netty:
  server:
    ssl: false
    port: 9999
    channel: io.netty.channel.socket.nio.NioServerSocketChannel
    boss-group:
      eventLoopGroup: io.netty.channel.nio.NioEventLoopGroup
    block-group:
      eventLoopGroup: io.netty.channel.nio.NioEventLoopGroup
      threads: 200
    socket:
      keepalive: true
      backlog: 1024
server:
  undertow:
    direct-buffers: true
    worker-threads: 200
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:keystore.p12 # 启用http2
    key-store-password: 123456 # 证书密码
    key-store-type: PKCS12 # 证书类型
    protocol: TLSv1.2 # 协议类型
    key-alias: undertow
